[bastion]

bastion-node ansible_host=34.206.71.38

[rke2_servers]
server-1 ansible_host=100.27.45.153
server-2 ansible_host=100.52.231.64

[rke2_agents]
worker-1 ansible_host=44.197.187.45
worker-2 ansible_host=44.199.246.165
worker-3 ansible_host=44.201.55.154

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/ubuntu/AbhayOrg.pem
ansible_python_interpreter=/usr/bin/python3
