---
- name: Join Second RKE2 Server
  hosts: server-2
  become: true
  gather_facts: true

  vars:
    rke2_server_ip: "100.27.45.153"

  pre_tasks:

    - name: Read token from Server-1
      slurp:
        src: /var/lib/rancher/rke2/server/node-token
      delegate_to: server-1
      register: server_token

    - name: Create RKE2 config directory
      file:
        path: /etc/rancher/rke2
        state: directory
        mode: "0755"

    - name: Create config.yaml
      copy:
        dest: /etc/rancher/rke2/config.yaml
        mode: "0600"
        content: |
          server: https://{{ rke2_server_ip }}:9345
          token: "{{ server_token.content | b64decode }}"

  tasks:

    - name: Download installer
      get_url:
        url: https://get.rke2.io
        dest: /tmp/install.sh
        mode: "0755"

    - name: Install RKE2 Server
      shell: |
        INSTALL_RKE2_TYPE=server sh /tmp/install.sh
      args:
        creates: /usr/local/bin/rke2

    - name: Enable service
      systemd:
        name: rke2-server
        enabled: yes

    - name: Start service
      systemd:
        name: rke2-server
        state: started

    - name: Wait until service is running
      service_facts:

    - name: Show service state
      debug:
        var: ansible_facts.services["rke2-server.service"].state
